
DROP TABLE IF EXISTS patch;
CREATE TABLE patch
(
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '唯一主键',
  new_version VARCHAR(45) NOT NULL COMMENT '新版本号 eg 1.0.0',
  old_version VARCHAR(45) NOT NULL COMMENT '旧版本号 eg 1.0.0',
  url VARCHAR(2083) NOT NULL COMMENT '补丁包下载地址',
  data BLOB NOT NULL COMMENT '补丁包映射的 patch 对象 JSON',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS resource;
CREATE TABLE resource
(
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '唯一主键',
  version_name VARCHAR(45) NOT NULL COMMENT '版本号名称 eg 1.0.0',
  version_code INT NOT NULL COMMENT '版本号编码 eg 1，2，3',
  data BLOB NOT NULL COMMENT '全量生产包映射 Resource 对象 Json',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
);
