-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 16:08:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ocat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ocat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocat` DEFAULT CHARACTER SET utf8mb4 ;
USE `ocat` ;

-- -----------------------------------------------------
-- Table `ocat`.`patch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocat`.`patch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '唯一主键',
  `new_version` VARCHAR(45) NOT NULL COMMENT '新版本号 eg 1.0.0',
  `old_version` VARCHAR(45) NOT NULL COMMENT '旧版本号 eg 1.0.0',
  `url` VARCHAR(2083) NOT NULL COMMENT '补丁包下载地址',
  `data` BLOB NOT NULL COMMENT '补丁包映射的 patch 对象 JSON',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `application_id` BIGINT NOT NULL,
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '补丁状态，1是不可用，2是可用。',
  PRIMARY KEY (`id`),
  INDEX `new_old_version_INDEX` (`new_version` ASC, `old_version` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocat`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocat`.`resource` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '唯一主键',
  `version_name` VARCHAR(45) NOT NULL COMMENT '版本号名称 eg 1.0.0',
  `data` BLOB NOT NULL COMMENT '全量生产包映射 Resource 对象 Json',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version_code` INT NOT NULL COMMENT '版本号编码 eg 1，2，3',
  `application_id` BIGINT NOT NULL,
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '版本资源状态，1 待发行，2 已发行',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `version_name_UNIQUE` (`version_name` ASC),
  UNIQUE INDEX `version_code_UNIQUE` (`version_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocat`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocat`.`application` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '应用名称',
  `app_id` VARCHAR(45) NOT NULL COMMENT '应用的唯一标识，相当于用户名。',
  `app_secret` VARCHAR(255) NOT NULL COMMENT '应用的密钥，相当于密码。',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `description` VARCHAR(255) NOT NULL COMMENT '应用描述',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `app_id_UNIQUE` (`app_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
